# Generated by Django 2.0.7 on 2018-07-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_identifier', models.CharField(max_length=255)),
                ('T_time', models.CharField(max_length=255)),
                ('C_imsi', models.CharField(max_length=255)),
                ('C_tmsi', models.CharField(max_length=255)),
                ('C_fcn', models.CharField(max_length=255)),
                ('C_time', models.CharField(max_length=255)),
                ('C_lon', models.CharField(max_length=255)),
                ('C_lat', models.CharField(max_length=255)),
            ],
        ),
    ]
