# Generated by Django 2.0.7 on 2018-07-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showData', '0003_auto_20180725_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='column',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
