# Generated by Django 2.0.7 on 2018-07-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showData', '0004_auto_20180725_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('t_identifier', models.CharField(max_length=255)),
                ('t_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LineTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_identifier', models.CharField(max_length=255)),
                ('t_time', models.CharField(max_length=255)),
                ('c_imsi', models.CharField(max_length=255)),
                ('c_tmsi', models.CharField(max_length=255)),
                ('c_fcn', models.CharField(max_length=255)),
                ('c_time', models.CharField(max_length=255)),
                ('c_lon', models.CharField(max_length=255)),
                ('c_lat', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
