# Generated by Django 2.0.7 on 2018-07-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showData', '0005_auto_20180725_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='linetxt',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showData.FileTxt'),
            preserve_default=False,
        ),
    ]
