# Generated by Django 2.0.7 on 2018-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showData', '0007_filepns_linepns'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetxt',
            name='store_time',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linetxt',
            name='store_time',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
