# Generated by Django 2.0.7 on 2018-09-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showData', '0010_auto_20180921_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetxt',
            name='machine_type',
            field=models.IntegerField(),
        ),
    ]
